stages:
  - build
  - package
  - public_test_repo
  - test

build:
  stage: build
  script:
    - docker build -t arch-selinux-build .

package:
  stage: package
  script: |
    mkdir pkgs
    docker run -v "$(pwd)/pkgs:/packages" --rm arch-selinux-build

  artifacts:
    paths:
      - pkgs/*

create public testing repo:
  stage: public_test_repo
  script: |
    rm -vf /srv/http/selinux-testing/*
    cp -v pkgs/* /srv/http/selinux-testing/
    repo-add /srv/http/selinux-testing/selinux-testing.db.tar.xz /srv/http/selinux-testing/*

prepare testing environment:
  stage: test
  script: |
    curl https://mirror.pkgbuild.com/iso/latest/archlinux-$(date +"%Y.%m.01")-x86_64.iso --output arch.iso
