stages:
  - build
  - package
  - public_test_repo
  - test

build:
  stage: build
  script:
    - docker build -t arch-selinux-build .

package:
  stage: package
  script: |
    mkdir pkgs
    docker run -v "$(pwd)/pkgs:/packages" --rm arch-selinux-build

  artifacts:
    paths:
      - pkgs/*

create public testing repo:
  stage: public_test_repo
  script: |
    rm -vf /srv/http/selinux-testing/*
    cp -v pkgs/* /srv/http/selinux-testing/
    repo-add /srv/http/selinux-testing/selinux-testing.db.tar.xz /srv/http/selinux-testing/*

prepare testing environment:
  stage: test
  script: |
    mkdir -vp /tmp/{boots/{,pkgs},arch}
    curl https://mirror.pkgbuild.com/iso/latest/archlinux-bootstrap-2020.12.01-x86_64.tar.gz --output archbootstrap.tar.gz
    tar xf archbootstrap.tar.gz -C /tmp/boots --strip-components 1
    cp -v pkgs/* /tmp/boots/pkgs
