stages:
  - build
  - package
  - public_test_repo
  - test

build:
  stage: build
  script:
    - docker build -t arch-selinux-build .

package:
  stage: package
  script: |
    mkdir pkgs
    docker run -v "$(pwd)/pkgs:/packages" --rm arch-selinux-build

  artifacts:
    paths:
      - pkgs/*

create public testing repo:
  stage: public_test_repo
  script: |
    rm -vf /srv/http/selinux-testing/*
    cp -v pkgs/* /srv/http/selinux-testing/
    repo-add /srv/http/selinux-testing/selinux-testing.db.tar.xz /srv/http/selinux-testing/*

prepare testing environment:
  stage: test
  script: |
    qemu-img create -f raw archlinux.raw 8G
    losetup /dev/loop0 -P archlinux.raw
    parted -s /dev/loop0 mklabel msdos
    parted -s -a optimal /dev/loop0 mkpart primary 0% 100%
    parted -s /dev/loop0 set 1 boot on
    mkfs.ext4 /dev/loop0p1
    tune2fs -L ROOT /dev/loop0p1
    mount /dev/loop0p1 /tmp/arch
