stages:
  - build
  - package
  - bootstrap_qemu
  - configure_qemu
  - test_selinux
  - cleanup

build:
  stage: build
  script:
    - docker build -t arch-selinux-build .

package:
  stage: package
  script: |
    mkdir pkgs
    docker run -v "$(pwd)/pkgs:/packages" --rm arch-selinux-build

  artifacts:
    paths:
      - pkgs/*

bootstrap qemu image:
  stage: bootstrap_qemu
  script: |
    repo-add pkgs/selinux-testing.db.tar.xz pkgs/*.zst
    cp -v /etc/pacman.conf pacman.local
    echo -e "[selinux-testing]\nSigLevel = Never\nServer = file:///$(pwd)/pkgs" >> pacman.local
    qemu-img create -f raw archlinux.raw 2G
    sudo losetup /dev/loop0 -P archlinux.raw
    sudo parted /dev/loop0 mklabel msdos
    sudo parted -a optimal /dev/loop0 mkpart primary 0% 100%
    sudo parted -s /dev/loop0 set 1 boot on
    sudo mkfs -t ext4 /dev/loop0p1
    sudo tune2fs -L ROOT /dev/loop0p1
    mkdir qemu
    sudo mount /dev/loop0p1 qemu/
    sudo pacstrap -C pacman.local qemu/ base linux grub
    echo -e "LABEL=ROOT / ext4 rw,relatime 0 1" > fstab  
    sudo mv fstab qemu/etc/fstab

    #sudo umount /dev/loop0p1
    #sudo losetup -d /dev/loop0
    #qemu-img convert -f raw -O qcow archlinux.raw archlinux.qcow2
  
#  artifacts:
#    paths: 
#      - archlinux.qcow2

configure qemu image:
  stage: configure_qemu
  script: |
    echo "arch-chroot"

test selinux functionality:
  stage: test_selinux
  script: |
    echo "qemu-system-x86_64"
