stages:
  - build
  - package

build:
  stage: build
  script:
    - docker build -t arch-selinux-build .

package:
  stage: package
  script: |
    mkdir pkgs
    docker run -v "$(pwd)/pkgs:/packages" --rm arch-selinux-build
    repo-add pkgs/selinux-testing.db.tar.xz pkgs/*

  artifacts:
    paths:
      - pkgs/*
