name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_all_packages:
    runs-on: ubuntu-18.04
    container: Dockerfile

    steps:
      - uses: actions/checkout@v2

      - name: testing
        run: |
          ls -la

#      - name: Build and install Arch Linux's SELinux support packages in a docker container
#        run: docker build -t arch-selinux-build . --security-opt seccomp=unconfined
#
#      - name: Run the container - built packages are transferred to build host
#        run: docker run -v "$(pwd)/pkgs:/packages" --rm arch-selinux-build
#
#      - name: Upload packages as artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: Arch Linux packages for SELinux support
#          path: pkgs

