name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_all_packages:
    runs-on: ubuntu-18.04
    container: 
      image: archlinux/archlinux:latest
      options: --privileged

    steps:
      - uses: actions/checkout@v2

      - name: testing
        run: |
          cat /proc/self/status
