name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_all_packages:
    runs-on: ubuntu-18.04
    container: 
      image: archlinux/archlinux:latest
      options: --privileged
      volumes:
        - pkgs:/packages

    steps:
      - uses: actions/checkout@v2

      - name: testing
        run: |
          mkdir -vp /startdir && \
          cp -Rv . /startdir && \
          pacman -q --noconfirm -Syu base base-devel expect git && \
          pacman --noconfirm -Sc && \
          rm -rf /var/cache/pacman/pkg/* && \
          ln -sf /usr/share/zoneinfo/UTC /etc/localtime && \
          useradd -g users -m builduser && \
          echo 'builduser ALL=(ALL) NOPASSWD: /usr/bin/pacman' >> /etc/sudoers && \
          echo 'builduser ALL=(ALL) NOPASSWD: /usr/bin/sh -c { pacman --noconfirm --ask=4 -U sudo-selinux/sudo-selinux-*.pkg.tar.zst && if test -e /etc/sudoers.pacsave ; then mv /etc/sudoers.pacsave /etc/sudoers ; fi }' >> /etc/sudoers && \
          echo 'MAKEFLAGS="-j$(nproc)"' >> /etc/makepkg.conf && \
          echo 'BUILDDIR=/build' >> /etc/makepkg.conf && \
          echo 'LOGDEST=/logdest' >> /etc/makepkg.conf && \
          mkdir -vp /packages /build /logdest && \
          chown -R builduser /startdir /packages /build /logdest && \
          sudo -u builduser /startdir/clean.sh && \
          sudo -u builduser /startdir/recv_gpg_keys.sh && \
          sudo -u builduser /startdir/build_and_install_all.sh && \
          rm -rf /startdir/*/src/ /startdir/*/pkg/ && \
          pacman --noconfirm -Sc && rm -rf /var/cache/pacman/pkg/* && \
          cp /startdir/*/*.pkg.tar.zst /packages

#      - name: Build and install Arch Linux's SELinux support packages in a docker container
#        run: docker build -t arch-selinux-build . --security-opt seccomp=unconfined
#
#      - name: Run the container - built packages are transferred to build host
#        run: docker run -v "$(pwd)/pkgs:/packages" --rm arch-selinux-build
#
      - name: Upload packages as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Arch Linux packages for SELinux support
          path: pkgs

